### ISSUE TITLE
Remove all reflection

### ISSUE THREAD

**Issue by ScarletRedMan** [MCPositron/MCPositron#7]
Use `Consumer<T>` and `Supplier<T>` instead of reflection.

- [ ] Level provider
- [ ] Generator
- [ ] Entity
- [ ] BlockEntity
- [ ] Item
- [ ] Block
- [ ] Player creation

**Comment by ScarletRedMan** [comment]
хочу вынести тому человеку ебасоску за то, что придумал использовать блядскую рефлексию и даже не пишет откуда он ее использует

**Comment by KoshakMineDEV** [comment]
Agree with u

**Comment by KoshakMineDEV** [comment]
Temporarily development of reflection removing is suspended. ScarletRedMan's SSD is dead

**Comment by KoshakMineDEV** [comment]
This issue maybe will be reopened if we will try again to remove reflection
